networks:
  jobstory_network:
    external: True

services:
  frontend:
    restart: unless-stopped
    image: node:22
    command: sh -c "corepack enable -- && yarn dev"
    working_dir: /app
    user: "1000:1000"

    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:4400
      SERVER_BACKEND_URL: http://backend:8000
      NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:8100
      NEXT_PUBLIC_KEYCLOAK_REALM: jobstory
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: jobstory-frontend

    volumes:
      - .:/app

    ports:
      - 4401:3000
    
    networks:
      - jobstory_network
