name: Test

on: push

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    name: Checkout and Install Dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Deps
        run: yarn install --frozen-lockfile
        
      - name: Run Tests
        run: yarn test
